//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaLuanTotNghiep
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VanDon
    {
        public long ID { get; set; }
        public Nullable<long> IDVD { get; set; }
        public string NameVD { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string DiemBD { get; set; }
        public string DiemDen { get; set; }
        public Nullable<long> IDKH { get; set; }
        public string NguoiNhan { get; set; }
        public string DiaChiNguoiNhan { get; set; }
        public string SDT { get; set; }
        public string SoXe { get; set; }
        public string SoTuyen { get; set; }
        public Nullable<long> IDHH { get; set; }
        public string CangBocHang { get; set; }
        public string CangDoHang { get; set; }
        public Nullable<double> CuocPhi { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<long> IDHTVC { get; set; }
        public Nullable<long> IDTTVD { get; set; }
    
        public virtual tbl_HangHoa tbl_HangHoa { get; set; }
        public virtual tbl_HTVanCHuyen tbl_HTVanCHuyen { get; set; }
        public virtual tbl_KhachHanga tbl_KhachHanga { get; set; }
        public virtual tbl_TinhTrangVanDon tbl_TinhTrangVanDon { get; set; }
    }
}
