//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaLuanTotNghiep
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HopDong
    {
        public long ID { get; set; }
        public Nullable<long> IDHD { get; set; }
        public string NameHD { get; set; }
        public Nullable<long> IDHH { get; set; }
        public Nullable<System.DateTime> NgayKy { get; set; }
        public Nullable<double> ChiPhi { get; set; }
        public Nullable<double> ChiPhiNop { get; set; }
        public Nullable<double> ChiPhiConLai { get; set; }
        public Nullable<long> IDDVVC { get; set; }
        public Nullable<long> IDDVKho { get; set; }
        public Nullable<long> IDKH { get; set; }
    
        public virtual tbl_KhachHanga tbl_KhachHanga { get; set; }
    }
}
