//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaLuanTotNghiep
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_HangHoa()
        {
            this.tbl_DichVuVCNB = new HashSet<tbl_DichVuVCNB>();
            this.tbl_DMVanDon = new HashSet<tbl_DMVanDon>();
            this.tbl_DVKho = new HashSet<tbl_DVKho>();
            this.tbl_DVVC = new HashSet<tbl_DVVC>();
            this.tbl_KhoNoiBo = new HashSet<tbl_KhoNoiBo>();
            this.tbl_VanDon = new HashSet<tbl_VanDon>();
        }
    
        public long ID { get; set; }
        public Nullable<long> IDHH { get; set; }
        public string TenHH { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<long> IDPLHH { get; set; }
        public Nullable<double> TrongLuong { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<long> IDDongGoi { get; set; }
        public Nullable<long> IDCangNoiDia { get; set; }
        public Nullable<long> IDContainerXNKhau { get; set; }
        public Nullable<long> IDHTVC { get; set; }
        public Nullable<long> IDKH { get; set; }
        public Nullable<long> IDXNKhau { get; set; }
    
        public virtual tbl_ContainerNoiDia tbl_ContainerNoiDia { get; set; }
        public virtual tbl_ContainerXNkhau tbl_ContainerXNkhau { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DichVuVCNB> tbl_DichVuVCNB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DMVanDon> tbl_DMVanDon { get; set; }
        public virtual tbl_DongGoiHH tbl_DongGoiHH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DVKho> tbl_DVKho { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DVVC> tbl_DVVC { get; set; }
        public virtual tbl_HHXuat_NhapKhau tbl_HHXuat_NhapKhau { get; set; }
        public virtual tbl_HTVanCHuyen tbl_HTVanCHuyen { get; set; }
        public virtual tbl_KhachHanga tbl_KhachHanga { get; set; }
        public virtual tbl_PhanLoaiHH tbl_PhanLoaiHH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KhoNoiBo> tbl_KhoNoiBo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_VanDon> tbl_VanDon { get; set; }
    }
}
