//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaLuanTotNghiep
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DMVanDon
    {
        public long ID { get; set; }
        public Nullable<long> IDVD { get; set; }
        public string NameVD { get; set; }
        public Nullable<long> Booking { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayKhoiHanh { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string DiemBD { get; set; }
        public string DiemDen { get; set; }
        public string Shipper { get; set; }
        public string Consignee { get; set; }
        public string NotifyParty { get; set; }
        public string TenTau { get; set; }
        public Nullable<long> SoChuyen { get; set; }
        public Nullable<long> IDPort { get; set; }
        public string PortOfLoading { get; set; }
        public string PortOfDischarging { get; set; }
        public string PreCarriage { get; set; }
        public string PlaceOfReceipt { get; set; }
        public string OnCarriage { get; set; }
        public string PlaceOfDelivery { get; set; }
        public string ContainerNoAndSealNo { get; set; }
        public Nullable<long> NumberOfPackages { get; set; }
        public string DescriptionOfGoods { get; set; }
        public string NetWeight { get; set; }
        public Nullable<long> GrossWeight { get; set; }
        public Nullable<long> Measurement { get; set; }
        public Nullable<long> FreightCollect { get; set; }
        public Nullable<long> FreightPrepaid { get; set; }
        public string PlaceAndDateOfIssue { get; set; }
        public string MBLNumber { get; set; }
        public string HBLNumber { get; set; }
        public string HinhThucVanCHuyen { get; set; }
        public Nullable<long> STT { get; set; }
        public Nullable<long> IDAir { get; set; }
        public Nullable<long> IDSea { get; set; }
        public Nullable<long> IDVessel { get; set; }
        public Nullable<long> IDDoor { get; set; }
        public Nullable<long> IDSender { get; set; }
        public Nullable<long> IDSenderQuocGia { get; set; }
        public Nullable<long> IDSenderDoor { get; set; }
        public Nullable<long> IDSenderPort { get; set; }
        public Nullable<long> IDSenderTerminal { get; set; }
        public string SenderAddressInPort { get; set; }
        public Nullable<long> IDSenderKho { get; set; }
        public Nullable<long> IDReceiver { get; set; }
        public Nullable<long> IDReceiverQuocGia { get; set; }
        public Nullable<long> IDReceiverDoor { get; set; }
        public Nullable<long> IDReceiverPort { get; set; }
        public Nullable<long> IDReceiverTerminal { get; set; }
        public Nullable<long> IDReceiverKho { get; set; }
        public string ReceiverAddressInPort { get; set; }
        public Nullable<int> EnumReceiverAgent { get; set; }
        public Nullable<long> IDKH { get; set; }
        public string NguoiNhan { get; set; }
        public string DiaChiNguoiNhan { get; set; }
        public string SDT { get; set; }
        public string SoXe { get; set; }
        public string SoTuyen { get; set; }
        public Nullable<long> IDHH { get; set; }
        public Nullable<double> CuocPhi { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<long> IDHTVC { get; set; }
        public string TinhTrangVanDon { get; set; }
        public Nullable<long> IDTTVD { get; set; }
    
        public virtual tbl_HangHoa tbl_HangHoa { get; set; }
        public virtual tbl_KhachHanga tbl_KhachHanga { get; set; }
        public virtual tblDMBaoGia tblDMBaoGia { get; set; }
        public virtual tblDMDoor tblDMDoor { get; set; }
        public virtual tblDMPort tblDMPort { get; set; }
        public virtual tblNhanSu tblNhanSu { get; set; }
    }
}
