//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaLuanTotNghiep
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DaiLi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_DaiLi()
        {
            this.tbl_KhachHanga = new HashSet<tbl_KhachHanga>();
        }
    
        public long ID { get; set; }
        public Nullable<long> IDDL { get; set; }
        public string Name { get; set; }
        public string SoDT { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public Nullable<long> IDHD { get; set; }
        public Nullable<long> IDTT { get; set; }
        public string SoTK { get; set; }
        public Nullable<long> IDKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KhachHanga> tbl_KhachHanga { get; set; }
    }
}
