//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaLuanTotNghiep
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDMBaoGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDMBaoGia()
        {
            this.tbl_DMVanDon = new HashSet<tbl_DMVanDon>();
        }
    
        public long ID { get; set; }
        public Nullable<long> IDJOB { get; set; }
        public Nullable<long> IDObject { get; set; }
        public string RefNo { get; set; }
        public string NameVI { get; set; }
        public string NameEN { get; set; }
        public Nullable<int> EnumQuotationType { get; set; }
        public Nullable<int> EnumCommondity { get; set; }
        public Nullable<System.DateTime> ValidityDate { get; set; }
        public Nullable<int> ValidityDuration { get; set; }
        public Nullable<System.DateTime> ExpityDate { get; set; }
        public Nullable<System.DateTime> SenderDate { get; set; }
        public Nullable<long> IDSale { get; set; }
        public Nullable<long> IDCurrency { get; set; }
        public string Note { get; set; }
        public string NoiDungBaoGia { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<bool> IsBookingConfirmed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DMVanDon> tbl_DMVanDon { get; set; }
    }
}
