//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaLuanTotNghiep
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDMDoor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDMDoor()
        {
            this.tbl_DMVanDon = new HashSet<tbl_DMVanDon>();
        }
    
        public long ID { get; set; }
        public Nullable<int> EnumTypeOfDoor { get; set; }
        public Nullable<long> IDQuocGia { get; set; }
        public Nullable<long> IDCity { get; set; }
        public string Code { get; set; }
        public string NameVI { get; set; }
        public string NameEN { get; set; }
        public string AddressVI { get; set; }
        public string AddressEN { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DMVanDon> tbl_DMVanDon { get; set; }
    }
}
