//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhoaLuanTotNghiep
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhanSu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNhanSu()
        {
            this.tbl_DMVanDon = new HashSet<tbl_DMVanDon>();
        }
    
        public long ID { get; set; }
        public Nullable<long> IDChucVu { get; set; }
        public Nullable<long> IDPhongBan { get; set; }
        public string MANHANSU { get; set; }
        public string MST { get; set; }
        public string HoTenVI { get; set; }
        public string HoTenEN { get; set; }
        public System.DateTime NamSinh { get; set; }
        public Nullable<int> GioiTinh { get; set; }
        public string QueQuan { get; set; }
        public string DiaChiThuongTru { get; set; }
        public string DiaChiHienTai { get; set; }
        public string SoCMT { get; set; }
        public string NoiCapCMT { get; set; }
        public Nullable<System.DateTime> NgayCapCMT { get; set; }
        public string SoHoChieu { get; set; }
        public string NoiCapHoChieu { get; set; }
        public Nullable<System.DateTime> NgayCapHoChieu { get; set; }
        public Nullable<System.DateTime> NgayHetHanHoChieu { get; set; }
        public Nullable<System.DateTime> NgayKyHopDong { get; set; }
        public byte[] PictureNV { get; set; }
        public string SoTaiKhoanNH { get; set; }
        public string DiDong { get; set; }
        public string Email { get; set; }
        public string SoTruong { get; set; }
        public Nullable<int> EnumTinhTrangHonNhan { get; set; }
        public Nullable<int> EnumNhomMau { get; set; }
        public Nullable<double> ChieuCao { get; set; }
        public Nullable<double> CanNang { get; set; }
        public Nullable<long> LUONGCOBAN { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DMVanDon> tbl_DMVanDon { get; set; }
    }
}
